- id: doi:10.15252/msb.20178124
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2018
  image: https://www.embopress.org/doi/full/10.15252/msb.20178124#msb178124-fig-0001
  buttons:
    - type: MOFA webpage
      link: https://biofam.github.io/MOFA2/index.html
  tags:
    - multi-modal data integration
    - probabilistic factor models

