- id: doi:10.15252/msb.20178124
  description: MOFA is a factor analysis model that provides a general framework for the integration of multi-omic data sets in an unsupervised fashion
  image: https://www.embopress.org/cms/10.15252/msb.20178124/asset/38d5fe53-2af9-469a-a44c-399133a490df/assets/graphic/msb178124-abs-0001-m.png
  date: 2018-06-18
  buttons:
    - type: MOFA webpage
      link: https://biofam.github.io/MOFA2/index.html
  tags:
    - multi-modal data integration
    - probabilistic factor models

