- id: doi:10.15252/msb.20178124
  type: paper
  description: MOFA is a factor analysis model that provides a general framework for the integration of multi-omic data sets in an unsupervised fashion
  date: 2018
  image: https://www.embopress.org/doi/full/10.15252/msb.20178124#msb178124-fig-0001
  buttons:
    - type: MOFA webpage
      link: https://biofam.github.io/MOFA2/index.html
  tags:
    - multi-modal data integration
    - probabilistic factor models

